# Generated by Django 2.0.5 on 2022-01-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0002_auto_20220113_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='data',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='quantidade',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
