# Generated by Django 2.0.5 on 2022-01-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0004_auto_20220113_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='data_final',
            field=models.DateTimeField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='descricao',
            field=models.CharField(default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='employee',
            name='data',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(max_length=15),
        ),
    ]
