# Generated by Django 2.0.5 on 2022-08-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_register', '0005_auto_20220117_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='', max_length=20)),
                ('valor_icms', models.FloatField(default=0)),
                ('valor_iss', models.FloatField(default=0)),
                ('valor_ipi', models.FloatField(default=0)),
                ('valor_cofins', models.FloatField(default=0)),
                ('valor_ir', models.FloatField(default=0)),
                ('valor_csll', models.FloatField(default=0)),
                ('class_fiscal', models.CharField(default='', max_length=15)),
                ('entrega', models.CharField(default='', max_length=40)),
                ('pagamento', models.CharField(default='', max_length=45)),
                ('valid_prop', models.CharField(default='', max_length=10)),
                ('hr_maq', models.FloatField(default=0)),
                ('mp', models.IntegerField(default=0)),
                ('t_superf', models.IntegerField(default=0)),
                ('t_term', models.IntegerField(default=0)),
                ('transp', models.IntegerField(default=0)),
                ('n_recorr', models.IntegerField(default=0)),
                ('preco_total', models.FloatField(default=0)),
                ('preco_icms', models.FloatField(default=0)),
                ('preco_ipi', models.FloatField(default=0)),
                ('preco_venda', models.FloatField(default=0)),
                ('bafo', models.FloatField(default='')),
                ('f_1250', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'employee_register_cotacao',
            },
        ),
        migrations.CreateModel(
            name='Ncm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=0)),
                ('aliquota', models.IntegerField(default=0)),
                ('icms', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'employee_register_ncm',
            },
        ),
        migrations.DeleteModel(
            name='TratSuperficialMag',
        ),
        migrations.DeleteModel(
            name='TratSuperficialMet',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='data',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='emp_code',
        ),
        migrations.AddField(
            model_name='employee',
            name='data_atual',
            field=models.DateField(default='2022-08-04', max_length=110),
        ),
        migrations.AddField(
            model_name='employee',
            name='det_alt_cli',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='dimensao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee_register.Dimensao'),
        ),
        migrations.AddField(
            model_name='employee',
            name='orcam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='trat_superf',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='employee',
            name='trat_term',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='alt_cli',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='proc_qual',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='req_cert',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='req_embal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee_register_employee',
        ),
        migrations.AlterModelTable(
            name='material',
            table='employee_register_material',
        ),
        migrations.AddField(
            model_name='cotacao',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee_register.Position'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='contato',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee_register.Empresa'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='fullname',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fullname_id', to='employee_register.Employee'),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='pn',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pn_id', to='employee_register.Employee'),
        ),
    ]
